language: php

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

matrix:
  include:
  allow_failures:
  - php: nightly
  - php: 7.1

before_script:
  - printf "\n" | pecl install -f redis
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source

script:
  - vendor/bin/phpunit

services:
  - redis-server
